# app/config/security.yml

jms_security_extra:
    secure_all_services: false
    expressions: true


security:
    providers:
        main:
            id: fos_user.user_provider.username

    encoders:
        Blb\UserBundle\Entity\User: sha512

    firewalls:
        # … le pare-feu « dev »
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Firewall principal pour le reste de notre site
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: /login
                check_path: /login_check
                # login success redirecting options (read further below)
                always_use_default_target_path: true
                default_target_path:            /admin/dashboard
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:
                path:       /logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
            

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
