<?php

namespace Blb\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function getReservations ()
    {
        
            $qb = $this->createQueryBuilder('resa');
            return $qb->getQuery()
                    ->getResult();
    }
}
