parameters:
#    blb_user.example.class: Blb\UserBundle\Example

services:
#    blb_user.example:
#        class: %blb_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
